# Site settings
title: "Achmad Nasirudin Sandi Resume"
description: "A resume of Achmad Nasirudin Sandi on GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Achmad Nasirudin Sandi"
resume_title:                   "Senior Software Development Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "i@gotcurio.us"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+62-811-898-815"
resume_contact_address:         "Malang, East Java, Indonesia"

resume_header_contact_info:     "Malang, East Java, Indonesia • +62-811-898-815 • i@gotcurio.us"
display_header_contact_info:    "false"

resume_header_intro: "<p>I am a curious senior-level software developer (OCP, Java SE since 2011) who focuses on Java technology and keeps eyes on other areas such as DevOps, Big Data, Cloud/ virtualization, hardware development, and relevant IT news to become a professional Staff Engineer. I aim to build a usable, user valued, low latency, high performance, outstanding quality, less time to market, cost effective-efficient, secure, interoperable, portable, and easy to maintain system using the following methodology/ concept/ approach: <ul>	<li>Specification by Example</li>	<li>User-Centered, Object-Oriented Analysis, and Domain-Driven Design</li>	<li>Keep It Simple Stupid -- Test-Driven Development</li>	<li>Continuous Integration, Delivery (Infrastructure as Code), and Documentation</li>	<li>Observable System and Measured Improvement</li></ul></p></p></p> I provide a software consultancy service."

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          false
resume_section_recognition:     true
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/achmadns"
#  resume_twitter_url:           "http://twitter.com/jglovier"
#  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/achmadnsandi"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://achmadns.gotcurio.us/"
  resume_medium_url:            "https://medium.com/@achmadns"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
